In [2]:
import numpy as np
a = [1, 2, 3]
print(a)

[1, 2, 3]


In [3]:
a = np.array(a)
print(a)

[1 2 3]


In [18]:
a.shape, help(a.dot), a.dot(a)

Help on built-in function dot:

dot(...) method of numpy.ndarray instance
    a.dot(b, out=None)
    
    Dot product of two arrays.
    
    Refer to `numpy.dot` for full documentation.
    
    See Also
    --------
    numpy.dot : equivalent function
    
    Examples
    --------
    >>> a = np.eye(2)
    >>> b = np.ones((2, 2)) * 2
    >>> a.dot(b)
    array([[2.,  2.],
           [2.,  2.]])
    
    This array method can be conveniently chained:
    
    >>> a.dot(b).dot(b)
    array([[8.,  8.],
           [8.,  8.]])



((3,), None, 14)

In [19]:
a.dtype

dtype('int64')

In [29]:
a = np.array(a, dtype=dict, ndmin=10)
a, a.dtype, a.shape

(array([[[[[[[[[[1, 2, 3]]]]]]]]]], dtype=object),
 dtype('O'),
 (1, 1, 1, 1, 1, 1, 1, 1, 1, 3))

In [24]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [31]:
a = np.array([1, 2, 3])
a ** 2

array([1, 4, 9])

In [36]:
a = np.arange(12, -1, -2)
np.sort(a)

array([ 0,  2,  4,  6,  8, 10, 12])

In [38]:
a = np.array([2.4, 2.5, 2.6])
a.round()

array([2., 3., 3.])

In [41]:
a = np.arange(10, 30, 2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [46]:
a = np.delete(a, [0, 2])
a

array([16, 20, 22, 24, 26, 28])

In [48]:
mass_arr = np.array([[1, 2, 3],[4, 5, 6]])
mass_arr.shape

(2, 3)

In [55]:
new_mass = mass_arr.reshape([3, 2])
new_mass, new_mass.shape
flatten_arr = new_mass.reshape(-1)
flatten_arr

array([1, 2, 3, 4, 5, 6])

In [58]:
x = flatten_arr.reshape(3, 2)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
x = x.reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
x.sum(axis=0), x.sum(axis=1)

(array([5, 7, 9]), array([ 6, 15]))

In [71]:
x.prod(axis=0), x.max(axis=1)

(array([ 4, 10, 18]), array([3, 6]))

In [74]:
a = np.array([1, 2, 0])
b = np.array([1, 2, 5])
c = a == b
c

array([ True,  True, False])

In [75]:
c.shape, c.sum()

((3,), 2)

In [76]:
y_pred = np.array([1, 2, 1, 2, 1, 1])
y_true = np.array([1, 2, 1, 1, 1, 1])
(y_pred == y_true).mean()

0.8333333333333334

In [88]:
a = np.eye(3, 3)
a[::-1]
b = np.ones([2, 10], dtype=np.int32)
b


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [106]:
a = np.array([[1, 2, 3],
            [4, 5, 6],
             [7, 8, 9]])

In [108]:
a[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])